### ISSUE TITLE
demo's broken

### ISSUE THREAD

**Issue by daslicious** [plouc/thumbor-toy#15]
demo's broken

**Comment by plouc** [comment]
@daslicious it's not a thumbor-toy issue, I use http://thumborize.me/ as thumbor server which seems to be broken.

**Comment by plouc** [comment]
@daslicious, guys from thumbor have fixed thumborize.me, so the thumbor-toy demo can now display images from it. I've also updated it to include new features like filters dragndrop, collapsible panes, themes…

**Comment by daslicious** [comment]
@plouc excellent, thanks for the update.
