### ISSUE TITLE
Add starwars sounds when panel moves

### ISSUE THREAD

**Issue by gmarchand** [plouc/thumbor-toy#18]
It seems to be urgent to add HTML5 sound when left and right panel moves : https://dl-web.dropbox.com/get/Autrewon.wav?_subject_uid=9707482&w=AADDUlUpZV5oslY7Q_6f379kPR9L4FUPFGeMLr74v3CHfA

**Comment by gmarchand** [comment]
cc @Wharenn to find the best sound

**Comment by mguern** [comment]
new sound

**Comment by mguern** [comment]
http://static2.canalplus.fr/gmarchand/fx4.wav

**Comment by gmarchand** [comment]
+1

**Comment by plouc** [comment]
sorry guys, but I won't implement this one…
