### ISSUE TITLE
demo doesn't work anymore

### ISSUE THREAD

**Issue by DanielRuf** [plouc/thumbor-toy#29]
There is nothing loading in the demo. I just get a 502 error in the browser console.

**Comment by plouc** [comment]
The demo server is managed by the guys from the main thumbor project, I just use free github static web hosting for the frontend.

**Comment by plouc** [comment]
Even the thumbor website seems to be broken, http://thumborize.me/?url=https%3A%2F%2Fi.ytimg.com%2Fvi%2FYCaGYUIfdy4%2Fmaxresdefault.jpg
